document:
  name: TDH022 â€“ TECHNICAL INTEROPERABILITY GUIDELINES AND API MANAGEMENT
  description: |
    These Guidelines define standards 
    and technologies that Public 
    Administrations will have to comply
    with to make their information 
    systems interoperable, in order to
    allow the information and data exchange
    between Administrations (central, regional
    and local), Public Entities and Third-Party
    Companies with the TDH Digital Ecosystem, 
    henceforth "Ecosystem" or "TDH", through 
    the TDH022.   
  tags:
    - Tourism
    - Interoperability
    - Digital Ecosystem
    - Ontologies
    - API
